### ISSUE TITLE
Basic Authorization Headers

### ISSUE THREAD

**Issue by izahoor-vwks** [ianneub/elasticsearch-to-s3#1]
Hi,

Can you please explain how can we pass username:password for Basic Authorization that is required to access the elasticsearch.

Elasticsearch that I want to access is using following plugin to control access to ES. https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin

Regards

**Comment by ianneub** [comment]
Unfortunately, I don't have a way to test this easily.

Did you try setting the `ELASTICSEARCH_SERVER` env var to something like this:
`ELASTICSEARCH_SERVER=http://username:password@example.com:9200`?

**Comment by izahoor-vwks** [comment]
I have tried two different combinations of commands but each failed with different error. I am listing down the commands and error below. 

_Using ES version : 5.4.0_

**Case1:**
`sudo docker run --rm -e "ES_URL=http://****:9200/" -e "ES_INDEX=******" -e "S3_BUCKET=******" -e "S3_KEY=es-test.gz" -e "AWS_ACCESS_KEY_ID=****" -e "AWS_SECRET_ACCESS_KEY=****" -e "AWS_DEFAULT_REGION=ap-southeast-1" -e “ELASTICSEARCH_SERVER=http://username:password@****:9200/” ianneub/elasticsearch-to-s3`

**Error:**
`/usr/local/bundle/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error': [401] Forbidden (Elasticsearch::Transport::Transport::Errors::Unauthorized)
	from /usr/local/bundle/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'
	from /usr/local/bundle/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
	from /usr/local/bundle/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/client.rb:128:in `perform_request'
	from /usr/local/bundle/gems/elasticsearch-api-1.0.18/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
	from /usr/local/bundle/gems/elasticsearch-api-1.0.18/lib/elasticsearch/api/actions/indices/get_settings.rb:65:in `get_settings'
	from /usr/src/app/lib/es_export.rb:68:in `backup'
	from export.rb:11:in `<main>'
zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
zlib(finalizer): the stream was freed prematurely.
Exporting http://****:9200//**** ...`

**Case2:**
`sudo docker run --rm -e "ES_URL=http://username:password@****:9200/" -e "ES_INDEX=****" -e "S3_BUCKET=****" -e "S3_KEY=es-test.gz" -e "AWS_ACCESS_KEY_ID=****" -e "AWS_SECRET_ACCESS_KEY=****" -e "AWS_DEFAULT_REGION=ap-southeast-1" -e “ELASTICSEARCH_SERVER=http://username:password@****:9200” ianneub/elasticsearch-to-s3`

**Error:**
`/usr/local/bundle/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error': [404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"","index_uuid":"_na_","index":""}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"","index_uuid":"_na_","index":""},"status":404} (Elasticsearch::Transport::Transport::Errors::NotFound)
	from /usr/local/bundle/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'
	from /usr/local/bundle/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
	from /usr/local/bundle/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/client.rb:128:in `perform_request'
	from /usr/local/bundle/gems/elasticsearch-api-1.0.18/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
	from /usr/local/bundle/gems/elasticsearch-api-1.0.18/lib/elasticsearch/api/actions/indices/get_settings.rb:65:in `get_settings'
	from /usr/src/app/lib/es_export.rb:68:in `backup'
	from export.rb:11:in `<main>'
zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
zlib(finalizer): the stream was freed prematurely.
Exporting http://username:password@****:9200//**** ...`

**Comment by ianneub** [comment]
Looks like `Case2` is properly handling the authentication. So now the problem is with `es_export.rb:68`. This is probably due to a version difference in ES. I was testing under an older version than 5.4.0.

Can you try cloning the code and upgrading the gem to `~>5.0`?
https://github.com/ianneub/elasticsearch-to-s3/blob/master/Gemfile#L4

There may be other issues with updates to the gem, but that might get you on the right track.

**Comment by izahoor-vwks** [comment]
I can give a try. I am not familiar with ruby so it might take me some time to respond back.

 Thanks

**Comment by ianneub** [comment]
Sorry @izahoor-vwks , that was a bad assumption on my part. Unfortunately I do not have the time currently to check into this.
